// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqsTxZn7b0BEJpYeeAzTdHHj31KqGdM4',
    appId: '1:677557829420:web:9010240ece02eee770f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    authDomain: 'trash-monitoring-app-88131.firebaseapp.com',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    measurementId: 'G-LND6PZK62F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBES3ugYqnsfFd-EozP0K1Sk-UofX69UAo',
    appId: '1:677557829420:android:c93571664673c01670f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxyvdi-3GsaDteGRsp6Jwn7iZ7G1LsGYw',
    appId: '1:677557829420:ios:aec4c2ef14093cdf70f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    iosClientId: '677557829420-e6svsfhpt6g91ai2c3opeone1hg36hug.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascoaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxyvdi-3GsaDteGRsp6Jwn7iZ7G1LsGYw',
    appId: '1:677557829420:ios:aec4c2ef14093cdf70f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    iosClientId: '677557829420-e6svsfhpt6g91ai2c3opeone1hg36hug.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascoaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqsTxZn7b0BEJpYeeAzTdHHj31KqGdM4',
    appId: '1:677557829420:web:43c8c6395c4af68870f689',
    messagingSenderId: '677557829420',
    projectId: 'trash-monitoring-app-88131',
    authDomain: 'trash-monitoring-app-88131.firebaseapp.com',
    storageBucket: 'trash-monitoring-app-88131.firebasestorage.app',
    measurementId: 'G-481FH20H0L',
  );

}