// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyFtSXbnOAx1rI2RnkW48y8bzQC2kei3A',
    appId: '1:53676250482:web:11227c77b3f8d519a679eb',
    messagingSenderId: '53676250482',
    projectId: 'ascoa-debug',
    authDomain: 'ascoa-debug.firebaseapp.com',
    storageBucket: 'ascoa-debug.firebasestorage.app',
    measurementId: 'G-WPF9SPM718',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfpf1x2KtM35xvNSigR5XZtq6xhj6ew8',
    appId: '1:53676250482:android:fb7ce5f82d874095a679eb',
    messagingSenderId: '53676250482',
    projectId: 'ascoa-debug',
    storageBucket: 'ascoa-debug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJljdqHLLMpyZOhwzuctid_QCsUDW0kg',
    appId: '1:53676250482:ios:836e682fb1de89bba679eb',
    messagingSenderId: '53676250482',
    projectId: 'ascoa-debug',
    storageBucket: 'ascoa-debug.firebasestorage.app',
    iosClientId: '53676250482-kbcavoafaarbpeho88f8va3eitiso2r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascoaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYJljdqHLLMpyZOhwzuctid_QCsUDW0kg',
    appId: '1:53676250482:ios:836e682fb1de89bba679eb',
    messagingSenderId: '53676250482',
    projectId: 'ascoa-debug',
    storageBucket: 'ascoa-debug.firebasestorage.app',
    iosClientId: '53676250482-kbcavoafaarbpeho88f8va3eitiso2r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascoaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyFtSXbnOAx1rI2RnkW48y8bzQC2kei3A',
    appId: '1:53676250482:web:7ea8a3186c46a153a679eb',
    messagingSenderId: '53676250482',
    projectId: 'ascoa-debug',
    authDomain: 'ascoa-debug.firebaseapp.com',
    storageBucket: 'ascoa-debug.firebasestorage.app',
    measurementId: 'G-CVQ03B0XE5',
  );

}